### PR TITLE
Mr adding features

### PR DESCRIPTION
**Pull request by MReeds**
git fetch --all
git checkout mr-addingFeatures
make sure that the edit and delete button doesnt show on a different users card
make sure you dont get an error in the console when you click the edit button on your message
make sure you the read me is updated

### CODE REVIEW

**Comment by michaelprince3** [comment]
Looks great!!!!

**Comment by ghost** [comment]
Everything works, ReadMe looks great!!!

**Comment by mKroogz** [comment]
🎉

**Comment by ghost** [comment]
Matt Reeds said to merge it!

**Pull request merged**
